koki-to/fleamarket_sample_78c

README.md

トップページのフロントデザインを作成します。
基準になるwebページなのではじめに作成します。

[FrontDesign_of_TopPage]

---

README.md
app/models/profile.rb
db/migrate/20200702090455_create_profiles.rb
db/schema.rb
spec/factories/profiles.rb
spec/models/profile_spec.rb

マイページのプロフィールに関するテーブルの構築とアソシエーションの設定を実施。
フリマサイトでマイページ上必要になる為

profileのテーブル作成

---

db/schema.rb

rails db:migrateを実行したら自動的にschema.rbが更新されてしまった。
なのでいったん新しいブランチに移動させ、マスターから隔離した。

[注意]schema.rbがrails db:migrateの自動更新で変更されてしまった！

---

app/models/item_image.rb
db/migrate/20200709013810_create_item_images.rb
db/schema.rb
spec/factories/item_images.rb
spec/models/item_image_spec.rb

##What
item_imageテーブルの実装とバリデーションテストを実装。
##Why
商品出品でimageが必須であるため、imageを投稿するitem_imageテーブルを実装した。

item_imageテーブルの実装

---

app/assets/stylesheets/modules/cards.scss
app/views/cards/new.html.haml

カード登録・変更ページの変更修正
ユーザーが商品購入時の支払いのために必要なため

[WIP]カード登録・変更ページのフロントデザイン

---

app/assets/stylesheets/modules/cards.scss
app/views/cards/show.html.haml

クレジットカード内容を変更ページの変更/修正
ユーザーがクレジットカードの変更をしたい時に必要なページのため

カード変更ページのフロントデザイン

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/new.html.haml

商品出品機能の追加をします。
- 画像は1枚以上必須
- 画像は複数枚投稿することができる
- 商品名が必須
- 商品の説明が必須
- カテゴリーの情報が必須
- ブランドについての情報は任意
- 商品の状態についての情報が必須
- 配送料の負担についての情報が必須
- 発送元の地域についての情報が必須
- 発送までの日数についての情報が必須
- 価格についての情報が必須
- フリマアプリの根幹の機能なので。
- 商品の出品が出来ないと他の機能の確認ができないので。

[WIP]商品出品機能の追加

---

app/assets/stylesheets/modules/items.scss
app/controllers/items_controller.rb
app/views/items/new.html.haml

商品出品機能の追加をします。
- 画像は1枚以上必須
- 画像は複数枚投稿することができる
- 商品名が必須
- 商品の説明が必須
- カテゴリーの情報が必須
- ブランドについての情報は任意
- 商品の状態についての情報が必須
- 配送料の負担についての情報が必須
- 発送元の地域についての情報が必須
- 発送までの日数についての情報が必須
- 価格についての情報が必須
- フリマアプリの根幹の機能なので。
- 商品の出品が出来ないと他の機能の確認ができないので。

[WIP]商品出品機能の追加（前回の続きから）

---

app/assets/javascripts/new_item.js
app/assets/javascripts/price.js
app/assets/stylesheets/modules/items.scss
app/models/item.rb
app/views/items/new.html.haml

[追加]出品機能のプルダウン

---

app/assets/javascripts/category_item.js
app/assets/stylesheets/modules/items.scss
app/controllers/items_controller.rb
app/views/items/get_category_children.json.jbuilder
app/views/items/get_category_grandchildren.json.jbuilder
app/views/items/new.html.haml
config/routes.rb

カテゴリー選択にjqueryを利用して非同期通信を実装する。
現在カテゴリー選択は常に3つのボックスが表示されているのでこれを改善するため。

[WIP]出品機能の実装（カテゴリー選択に非同期通信を実装する）

---

.gitignore
app/controllers/items_controller.rb
app/views/items/new.html.haml

[追加]enumの機能

---

app/assets/stylesheets/modules/items.scss
app/controllers/items_controller.rb

クレジットカードの登録、削除、購入機能を実装した。
app/controllers/items_controller.rb(payで購入機能)
/cards_controller.rb(new,createで登録機能、destroyで削除機能)
app/aseets/javascripts/payjp.js (登録機能のjs)
payjpの方で実際に売り上げの記録を確認しています。
フリマアプリ完成の必須機能のため。

クレジットカードの登録、削除、購入機能

---

app/assets/javascripts/category_item.js
app/assets/stylesheets/modules/items.scss
app/assets/stylesheets/modules/items_show.scss
app/controllers/items_controller.rb
app/views/items/new.html.haml
app/views/items/show.html.haml
config/routes.rb

出品機能のおけるカテゴリー選択の修正

---

app/assets/javascripts/length_counter.js
app/assets/stylesheets/modules/home.scss
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/home/index.html.haml
app/views/items/new.html.haml
app/views/users/show.html.haml

- 商品出品画面で必要になる文字数カウンターのJSを追加する。
- ホーム画面の一覧表示の件数を制限する。
- 最新と既存のそれぞれの最初から4件だけを表示する。

文字カウンターの追加と一覧表示の修正

---

app/controllers/items_controller.rb
app/views/items/edit.html.haml
app/views/items/new.html.haml
db/migrate/20200709013810_create_item_images.rb
db/schema.rb

出品されたカテゴリー情報が編集画面に引き継がれるようにした。
編集画面にカテゴリーが引き継がれていなかったため、修正した。

商品編集　カテゴリー機能の実装

---

app/controllers/cards_controller.rb
app/controllers/users_controller.rb
app/models/item.rb
app/models/user.rb

cardのdestroyアクションの不具合を修正した。
フリマアプリ完成のため

[修正]cardのdestroyアクション

---

app/controllers/items_controller.rb
app/models/item.rb
app/models/user.rb
app/views/items/index.html.haml
app/views/items/search.html.haml
app/views/items/show.html.haml
app/views/template/_header.html.haml
config/routes.rb

seachアクションの追加
app/views/items/search.html.haml(searchアクションのview)
app/controllers/items_controller.rb(searchアクション)
挙動確認
https://gyazo.com/f3e478696f2725016370f344d89622e6
フリマアプリの追加実装のため

[追加]searchアクションの追加

---

app/views/items/show.html.haml

アイテム詳細ページの売り切れ表示
フリマアプリの完成度を高める為

[追加]item.showのsold表示

---

app/views/template/_header.html.haml

トップページの表記を修正した。
フリマアプリの完成度を高めるため。

home.indexの表記

---

app/assets/javascripts/slick.js
app/controllers/items_controller.rb

画像スクロールのslick.jsの修正、cardコントローラーの修正を行った
フリマアプリ完成のため

[修正]slick.jsのエラー

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_flash.scss
app/assets/stylesheets/modules/cards.scss
app/assets/stylesheets/modules/items.scss
app/assets/stylesheets/modules/items_confirm.scss
app/assets/stylesheets/modules/items_search.scss
app/assets/stylesheets/modules/items_show.scss
app/assets/stylesheets/modules/user.scss
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/items/search.html.haml
app/views/users/edit.html.haml

サーチ結果を表示するビューの作成
サーチ結果をユーザーが閲覧するため

サーチ結果のビューの作成

---

app/controllers/items_controller.rb
app/models/user.rb

item.createアクション
